### ISSUE TITLE
Code formatting via context menu does not work properly and diminishes the syntax highlighting 

### ISSUE THREAD

**Issue by emg110** [dragmz/vscode-teal#2] opened 2022-12-22 11:36 UTC
When formatting code using the context menu format document feature, it sets two tab indentations which defy the syntax highlighting and makes all the code red for some reason.
![Screenshot 2022-12-22 at 14 34 06](https://user-images.githubusercontent.com/1900448/209125982-874e91a9-92ad-4d9c-a312-296e9a5e3574.png)
![Screenshot 2022-12-22 at 14 34 23](https://user-images.githubusercontent.com/1900448/209125988-6d0cbab7-44fa-4c04-bff9-e9d35b121520.png)

**Comment by dragmz** [comment] 2022-12-22 12:39
Thanks, have you got any other TEAL syntax highlighting extension installed?

**Comment by emg110** [comment] 2022-12-22 12:43
I disabled obsidians Extention and after reload still not working:
![Screenshot 2022-12-22 at 15 41 49](https://user-images.githubusercontent.com/1900448/209136866-dbc0fd88-8ca0-47e8-9608-f1368d0f5a08.png)

**Comment by dragmz** [comment] 2022-12-22 15:22
Still seems like some interference to me. Would you mind checking if you have any other extensions contributing to the teal language in: `VS Code -> Extensions -> [Extension] -> Feature Contributions -> Languages (where ID = 'teal')`?

**Comment by dragmz** [comment] 2023-01-23 18:15
Closing because of no input and I can't reproduce.

**Closed as not planned** 2023-01-23 18:15 UTC
